// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtytvoRxe8TlHMLbihdbTtolAL4uxnHrc',
    appId: '1:418497274240:web:2e8b547d553c0c3749e165',
    messagingSenderId: '418497274240',
    projectId: 'fasttravel-4991',
    authDomain: 'fasttravel-4991.firebaseapp.com',
    databaseURL: 'https://fasttravel-4991-default-rtdb.firebaseio.com',
    storageBucket: 'fasttravel-4991.appspot.com',
    measurementId: 'G-NT4NP6S7G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnrr3H_vB-ZA9dVRlPxfpJeZjtkIPdDCw',
    appId: '1:418497274240:android:e0e9c7715a6acf9849e165',
    messagingSenderId: '418497274240',
    projectId: 'fasttravel-4991',
    databaseURL: 'https://fasttravel-4991-default-rtdb.firebaseio.com',
    storageBucket: 'fasttravel-4991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNelqIdeTgAmVjaXuRO1bVRb8FSj6ZMDE',
    appId: '1:418497274240:ios:909b92015f81319449e165',
    messagingSenderId: '418497274240',
    projectId: 'fasttravel-4991',
    databaseURL: 'https://fasttravel-4991-default-rtdb.firebaseio.com',
    storageBucket: 'fasttravel-4991.appspot.com',
    iosClientId: '418497274240-mrepjor7f36n60jlba7qiqje0iu1s9tv.apps.googleusercontent.com',
    iosBundleId: 'com.example.fasttravel',
  );
}
